import styles from '../styles/Home.module.css'
import Head from 'next/head';
import { app } from '../firebaseConfig';
import { useEffect } from 'react';
import { getAuth, createUserWithEmailAndPassword } from 'firebase/auth'
import { useState } from 'react';
import { useRouter } from 'next/router';
export default function Register() {
    const auth = getAuth();
    const router = useRouter();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    // quando se carrega no botão o programa vai pegar nos dados e enviar para o firebase. Se receber resposta continua o programa
    const signUp = () => { 
        createUserWithEmailAndPassword(auth, email, password)
            .then((response) => {
                router.push('/')
            })
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Next CRUD AUTH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Registar Conta</h1>

                <input
                    placeholder='Email'
                    className={styles.inputBox}
                    onChange={(event) => setEmail(event.target.value)}
                    value={email}
                    type='email'
                />
                <input
                    placeholder='Password'
                    className={styles.inputBox}
                    onChange={(event) => setPassword(event.target.value)}
                    value={password}
                    type='password'
                />

                <button
                    className={styles.button}
                    onClick={signUp}
                >Sign Up</button>
            </main>
        </div>
    )
}